version: '3.8'

services:
  movies:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - movies-db
  movies-db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=movies
      - MYSQL_USER=movies
      - MYSQL_PASSWORD=movies
      - MYSQL_DATABASE=movies_dev

volumes:
  mysql_data: